services:
  website:
    build:
      context: .
      dockerfile: ./apps/website/Dockerfile
    volumes:
      - ./apps/website:/app # Sync project files with the container
      - /app/node_modules # Prevent node_modules syncing with host
    ports:
      - "5173:5173" # Map Vite's default dev server port
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes (required for some environments)

