# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  asp-backend:
    image: asp-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: apps/asp-backend/Dockerfile
    ports:
      - 5212
    develop:
      watch:
        - action: rebuild
          path: .
  website:
    image: website
    build:
      context: .
      dockerfile: apps/website/Dockerfile
    volumes:
      - ./apps/website:/app # Sync project files with the container
      - /app/node_modules # Prevent node_modules syncing with host
    ports:
      - 5173 # Map Vite's default dev server port
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes (required for some environments)
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ets-zemun
      POSTGRES_PASSWORD: jfcm09iu43f85fjdskcnxmn
      POSTGRES_DB: ets-zemun
    ports:
      - "5000:5432"
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - website
      - asp-backend
