# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  etszemun:
    image: etszemun
    build:
      context: .
      dockerfile: apps/asp-backend/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5212:5212
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
