services:
  asp-backend:
    image: andrejnenadic/ets-zemun-backend
    volumes:
      - aspnet-data:/app/keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${CONN_STRING}
    build:
      context: .
      dockerfile: apps/asp-backend/Dockerfile
    ports:
      - 5000:5000

volumes:
  aspnet-data:
