services:
  backend:
    image: andrejnenadic/ets-zemun-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 5000:5000
