services:
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: apps/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"

  website:
    image: website
    build:
      context: .
      dockerfile: apps/website/Dockerfile
    volumes:
      - ./apps/website:/app # Sync project files with the container
      - /app/node_modules # Prevent node_modules syncing with host
    ports:
      - 5173 # Map Vite's default dev server port
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes (required for some environments)

  admin-panel:
    image: admin-panel
    build:
      context: .
      dockerfile: apps/admin-panel/Dockerfile
    volumes:
      - ./apps/admin-panel:/app
      - /app/node_modules
    ports:
      - 5174
    environment:
      - CHOKIDAR_USEPOLLING=true

  asp-backend:
    image: asp-backend
    volumes:
      - aspnet-data:/app/keys
    secrets:
      - google-auth
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: apps/asp-backend/Dockerfile
    ports:
      - 5000
    develop:
      watch:
        - action: rebuild
          path: .

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ets-zemun
      POSTGRES_PASSWORD: jfcm09iu43f85fjdskcnxmn
      POSTGRES_DB: ets-zemun
    ports:
      - "5000:5432"

secrets:
  google-auth:
    file: secrets.json

volumes:
  aspnet-data:
