[alias]
    "@styles" = "public/sass"
    "@assets" = "src/assets"
    "@data" = "src/assets/json-data/data"
    "@contexts" = "src/contexts"
    "@hooks" = "src/hooks"
    "@components" = "src/components"