/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProfilesSchema {
  profiles: {
    /**
     * Name of the profile
     */
    name: string;
    /**
     * Short description of the profile
     */
    description: string;
    /**
     * Path to the image of the profile
     * MUST start with ''@images/profiles/''
     * MUST end with one of the following extensions: .jpg, .jpeg, .png, .gif, .bmp, .webp, .tiff, .svg
     * The referenced image MUST exist in the '/public/images/profiles/' folder
     */
    imagePath: string;
    /**
     * URL extensions of the page fully describing the profile
     * Each URL extension MUST only contains lowercase letters and hyphens
     *
     * @minItems 1
     */
    profileURL: [string, ...string[]];
  }[];
}
