import AppFooter from "@/components/app-footer/app-footer";
import AppHeader from "@/components/app-header/app-header";
import Scroller from "@/components/scroller/scroller";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import Script from "next/script";
import "./index.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages({ locale });

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <div id="root">
            <AppHeader />

            <div id="page-content">{children} </div>

            <Scroller />

            <AppFooter />
          </div>
        </NextIntlClientProvider>

        <Script src="https://kit.fontawesome.com/053e158ed1.js"></Script>
      </body>
    </html>
  );
}
